Repository Tanmaydeep/hacktober-fest-2025, pull requests merged in 2025-10, with the labels that each got.

#1 hf25: added ipfs-indexing project
  IPFS-metadaa-indexing/README.md
  IPFS-metadaa-indexing/index.js
  IPFS-metadaa-indexing/package.json
  IPFS-metadaa-indexing/src/app.js
  IPFS-metadaa-indexing/src/config/db.js
  IPFS-metadaa-indexing/src/config/pinata.js
  IPFS-metadaa-indexing/src/controller/hackathonController.js
  IPFS-metadaa-indexing/src/controller/projectsController.js
  IPFS-metadaa-indexing/src/controller/teamsController.js
  IPFS-metadaa-indexing/src/controller/usersController.js
  IPFS-metadaa-indexing/src/model/masterSchema.js
  IPFS-metadaa-indexing/src/routes/hackathonRoutes.js
  IPFS-metadaa-indexing/src/routes/projectsRoutes.js
  IPFS-metadaa-indexing/src/routes/teamRoutes.js
  IPFS-metadaa-indexing/src/routes/userRoutes.js
  IPFS-metadaa-indexing/src/utils/createItem.js
  IPFS-metadaa-indexing/src/utils/helper.js
  IPFS-metadaa-indexing/src/utils/ipfs.js
Labels: hf-approved

#3 hf25: added an progress-tracking agentic ai bot
  agentic-tracker/.gitignore
  agentic-tracker/README.md
  agentic-tracker/core/__pycache__/document_parser.cpython-311.pyc
  agentic-tracker/core/__pycache__/progress_tracker.cpython-311.pyc
  agentic-tracker/core/__pycache__/repo_connector.cpython-311.pyc
  agentic-tracker/core/__pycache__/report_generator.cpython-311.pyc
  agentic-tracker/core/__pycache__/task_extractor.cpython-311.pyc
  agentic-tracker/core/document_parser.py
  agentic-tracker/core/progress_tracker.py
  agentic-tracker/core/repo_connector.py
  agentic-tracker/core/report_generator.py
  agentic-tracker/core/task_extractor.py
  agentic-tracker/main.py
  agentic-tracker/requirements.txt
Labels: hf-approved

#8 Update README.md
  README.md
Labels: enhancement, hf-approved, Hacktober-fest-accepted

#9 hf25: Tauri app
  tauri-app/.eslintrc.json
  tauri-app/.gitignore
  tauri-app/README.md
  tauri-app/next.config.js
  tauri-app/package.json
  tauri-app/postcss.config.js
  tauri-app/public/next.svg
  tauri-app/public/vercel.svg
  tauri-app/src-tauri/.gitignore
  tauri-app/src-tauri/Cargo.lock
  tauri-app/src-tauri/Cargo.toml
  tauri-app/src-tauri/build.rs
  tauri-app/src-tauri/icons/128x128.png
  tauri-app/src-tauri/icons/128x128@2x.png
  tauri-app/src-tauri/icons/32x32.png
  tauri-app/src-tauri/icons/Square107x107Logo.png
  tauri-app/src-tauri/icons/Square142x142Logo.png
  tauri-app/src-tauri/icons/Square150x150Logo.png
  tauri-app/src-tauri/icons/Square284x284Logo.png
  tauri-app/src-tauri/icons/Square30x30Logo.png
  tauri-app/src-tauri/icons/Square310x310Logo.png
  tauri-app/src-tauri/icons/Square44x44Logo.png
  tauri-app/src-tauri/icons/Square71x71Logo.png
  tauri-app/src-tauri/icons/Square89x89Logo.png
  tauri-app/src-tauri/icons/StoreLogo.png
  tauri-app/src-tauri/icons/icon.icns
  tauri-app/src-tauri/icons/icon.ico
  tauri-app/src-tauri/icons/icon.png
  tauri-app/src-tauri/src/main.rs
  tauri-app/src-tauri/tauri.conf.json
  tauri-app/src/app/CodeBlock.tsx
  tauri-app/src/app/favicon.ico
  tauri-app/src/app/globals.css
  tauri-app/src/app/layout.tsx
  tauri-app/src/app/page.tsx
  tauri-app/tailwind.config.js
  tauri-app/tsconfig.json
  tauri-app/yarn.lock
Labels: hf-approved, Hacktober-fest-accepted
